[project]
name = "erc-20"
version = "0.1.0"
description = "Effortlessly interact with ERC-20 contracts in Python"
authors = [
    { name = "Xurvan", email = "xurvan@tutanota.com" },
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = { text = "Apache-2.0" }

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"
